export const data = [
  {
    name: 'Matt Green',
    outlet: 'Content Creator',
    territory: 'UK',
    notes: '9x16 safe footage. UHD',
    status: 'COMPLETED',
    interviewDuration: '300',
    virtual: false,
  },
  {
    name: 'Gavin Spoors',
    outlet: 'Filmhounds',
    territory: 'Germany',
    notes: 'Zoom name: GS iPhone',
    status: 'COMPLETED',
    interviewDuration: '300',
    virtual: true,
  },
  {
    name: 'Hannah Jackson',
    outlet: 'Odeon Socials',
    territory: 'France',
    notes: 'Zoom name: GS iPhone',
    status: 'IN INTERVIEW',
    interviewDuration: '300',
    virtual: true,
  },
  {
    name: 'Lucy Fenwick',
    outlet: 'Picturehouse: Love of Cinema Podcast',
    territory: 'Netherlands',
    notes: '',
    status: 'ON DECK',
    interviewDuration: '300',
    virtual: true,
  },
  {
    name: 'Chris Hewitt',
    outlet: 'Empire Podcast',
    territory: 'UK',
    notes: '',
    status: '',
    interviewDuration: '300',
    virtual: false,
  },
  {
    name: 'Owen Bush',
    outlet: 'BAFTA Socials',
    territory: 'UK',
    notes: '',
    status: 'CANCELLED',
    interviewDuration: '300',
    virtual: false,
  },
]
