export const data = [
  {
    id: 'interview-1',
    name: 'Matt Green',
    outlet: 'Content Creator',
    startTime: '',
    territory: 'UK',
    notes: '9x16 safe footage. UHD',
    status: 'COMPLETED',
    interviewDuration: '300',
    virtual: false,
    isBreak: false,
    breakText: '',
  },
  {
    id: 'interview-2',
    name: 'Gavin Spoors',
    outlet: 'Filmhounds',
    startTime: '',
    territory: 'Germany',
    notes: 'Zoom name: GS iPhone',
    status: 'COMPLETED',
    interviewDuration: '300',
    virtual: true,
    isBreak: false,
    breakText: '',
  },
  {
    id: 'interview-3',
    name: 'Hannah Jackson',
    outlet: 'Odeon Socials',
    startTime: '',
    territory: 'France',
    notes: 'Zoom name: GS iPhone',
    status: 'IN INTERVIEW',
    interviewDuration: '300',
    virtual: true,
    isBreak: false,
    breakText: '',
  },
  {
    id: 'interview-4',
    name: 'Lucy Fenwick',
    outlet: 'Picturehouse: Love of Cinema Podcast',
    startTime: '',
    territory: 'Netherlands',
    notes: '',
    status: 'ON DECK',
    interviewDuration: '300',
    virtual: true,
    isBreak: false,
    breakText: '',
  },
  {
    id: 'interview-5',
    name: '',
    outlet: '',
    startTime: '',
    territory: '',
    notes: '',
    status: 'IN INTERVIEW',
    interviewDuration: '300',
    virtual: false,
    isBreak: true,
    breakText: 'Reset to virtual',
  },
  {
    id: 'interview-6',
    name: 'Chris Hewitt',
    outlet: 'Empire Podcast',
    startTime: '',
    territory: 'UK',
    notes: '',
    status: '',
    interviewDuration: '300',
    virtual: false,
    isBreak: false,
    breakText: '',
  },
  {
    id: 'interview-7',
    name: 'Owen Bush',
    outlet: 'BAFTA Socials',
    startTime: '',
    territory: 'UK',
    notes: '',
    status: 'CANCELLED',
    interviewDuration: '300',
    virtual: false,
    isBreak: false,
    breakText: '',
  },
]
